services:  
  flask-app:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
      - redis      
    environment:
      - FLASK_ENV=development       # replaces debug: true
      - CELERY_BROKER_URL=redis://redis:6379/0
      - MONGO_URI=mongodb://admin:123@mongodb:27017/code_review_db?authSource=admin

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    depends_on:
      - mongodb
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - MONGO_URI=mongodb://admin:123@mongodb:27017/code_review_db?authSource=admin

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: code_review_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: